apiVersion: v1
kind: Service
metadata:
  labels:
    app: amancevice-devops
  name: amancevice-devops-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6000
  selector:
    app: amancevice-devops
  type: ClusterIP
