apiVersion: v1
kind: Service
metadata:
  labels:
    app: airflow-devops
  name: airflow-devops-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: airflow-devops
  type: ClusterIP
